/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useEffect, useRef } from "react";

export function Character({ animation, ...props }) {
  const group = useRef();
  const model = useGLTF("/models/AdventurerAnimatedExport.glb");
  const animationFromHook = useAnimations(model.animations, group);

  const { animationName } = useControls({animationName: {options: animationFromHook.names}})
  
  // useEffect(() => {
  //   animationFromHook.actions[model.animation]?.reset().fadeIn(0.24).play();
  //   return () => animationFromHook.actions?.[model.animation]?.fadeOut(0.24);
  // }, [model.animation, animationFromHook.actions]);

      useEffect(() =>
    {
        const action = animationFromHook.actions[animationName]
        action
            .reset()
            .fadeIn(0.5)
            .play()

        return () =>
        {
            action.fadeOut(0.5)
        }
    }, [ animationName ])

  
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive scale={.8} object={model.scene} />
    </group>
  );
}

useGLTF.preload("/models/AdventurerAnimatedExport.glb");
